version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${ADMIN}"
      MONGO_INITDB_ROOT_PASSWORD: "${ADMIN_PASSWORD}"
    volumes:
      - mongo-data:/data/db
    networks:
      - private_net

  node-api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_SERVER: "${SERVER}"
      ME_CONFIG_MONGODB_PORT: "${PORT}"
      ME_CONFIG_MONGODB_ADMINUSERNAME: "${ADMIN}"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "${ADMIN_PASSWORD}"
      ME_CONFIG_BASICAUTH_USERNAME: "${USER}"
      ME_CONFIG_BASICAUTH_PASSWORD: "${USER_PASSWORD}"

    ports:
      - 8081:8081

    networks:
      - private_net
      - public_net

volumes:
  mongo-data:
    driver: local
    external: false

networks:
  private_net:
    driver: bridge
  public_net:
    driver: bridge